### ISSUE TITLE
Change Dockerfile for base image from centos:lastest to centos:7.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/container-dtc-nwp#13]
The centos:latest tag recently switched from centos:7 to centos:8.  But that breaks the builds because not all of the required packages are available for centos:8 yet.

**Comment by mkavulich** [comment]
Change made (https://github.com/NCAR/CCCP/commit/04c0ee3f3d045951a273ade759348882d581748e)

Awaiting test results from Docker Hub automated tests

**Comment by mkavulich** [comment]
All tests passed
