### ISSUE TITLE
Update GFS S3 pull script

### ISSUE THREAD

**Issue by michelleharrold** [NCAR/container-dtc-nwp#16]
Update GFS S3 pull script to no longer pull and cat together individual fields...can now pull full file from NOAA site.

Email from Jack Settelmaier:

Just today I was made aware that the ability to see an easy to read Index of what is available in the GFS bucket has been re-enabled.
https://noaa-gfs-bdp-pds.s3.amazonaws.com/index.html 

Using that index, and navigating into a directory tree, one can see that both the .anl and .f000 files are being made available in this bucket at quarter degree spatial resolution.
https://noaa-gfs-bdp-pds.s3.amazonaws.com/gfs.20200116/12/gfs.t12z.pgrb2.0p25.anl
https://noaa-gfs-bdp-pds.s3.amazonaws.com/gfs.20200116/12/gfs.t12z.pgrb2.0p25.f000

**Comment by fossell** [comment]
I think we updated this now and can close this issue, @michelleharrold can you confirm?

**Comment by michelleharrold** [comment]
Yes!
