### ISSUE TITLE
Get METviewer to work in Singularity

### ISSUE THREAD

**Issue by mkavulich** [NCAR/container-dtc-nwp#23]
There does not appear to be a proper analog for docker-compose in Singularity. We need to find out if it's possible to re-structure how the METviewer container works in order to work in both Singularity and Docker, or else create a specialized METviewer container specifically for Singularity.

**Comment by mkavulich** [comment]
There now *is* a proper analog for docker-compose in Singularity (https://singularityhub.github.io/singularity-compose/#/). @michelleharrold will try to get that working first.

**Comment by JohnHalleyGotway** [comment]
@JohnHalleyGotway and @michelleharrold met on 2/22/2022 to brainstorm. Here are some notes:
- Singularity-Compose does NOT currently support orchestration between multiple containers. So we can't have METviewer and MySQL in separate images.
- Considered changing the METviewer base image to mysql:5.7 but that uses the apt-get package manager and may not actually be necessary.
- We note that the MV Dockerfile ALREADY install mysql via yum. Perhaps we just need to reconfigure the EXISTING image to run MySQL locally?
-

**Comment by JohnHalleyGotway** [comment]
@TatianaBurek, can you please read through the [comment](https://github.com/NCAR/container-dtc-nwp/issues/23#issuecomment-1048113599) above, and then take a look at this [feature branch](https://github.com/NCAR/container-dtc-nwp/tree/feature/issue_23_mv_singularity/components/metviewer/METviewer). Specifically, please see the TODO list on this [line](https://github.com/NCAR/container-dtc-nwp/blob/bb6b33e462242199d76bb9bc1302b314cba3aa6c/components/metviewer/METviewer/Dockerfile_for_singularity#L72) of Dockerfile_for_singularity.

@michelleharrold and @JohnHalleyGotway were not sure how to accomplish these steps. 2 questions...
- Is this the right approach?
- Are you willing/able to help us on this?

**Comment by TatianaBurek** [comment]
I agree that the approach to use mysql-docker repo is promising but I do have some concerns like the base OS compatibility oraclelinux:7-slim vs dtcenter/base_image:simple. I also try to use other Dockerfiles that install mysql  but they all were created with the assumption that it would be the DB server only and any additions like Tomcat or R did not work. I didn't spend a lot of time on this task so I can't say for sure that it can't be done.
I can give it a try. What is the key # for charging?

**Comment by michelleharrold** [comment]
@TatianaBurek -- thanks for offering to give it a try!

@jwolff-ncar -- if you are okay with Tatiana giving this a try, can you provide her the charge key?

**Comment by TatianaBurek** [comment]
Update in short:
I was able to install and run the database in the same container as METviewer and it's components.
But:
- I could not make MySQL database work so I end up with MariaDB instead. It comes with different docker-entrypoint.sh and installation method
- I had to use FROM centos:7 instead of dtcenter/base_image:simple 
- Tomcat has to be started  by hand from the container vs the old way when it was started automatically using the command from the Dockerfile
- I did not update GitHub yet
Do you think that this is OK and will work for you?
Should I commit my work to GItHub?

**Comment by JohnHalleyGotway** [comment]
@TatianaBurek, yes, please do commit your work in progress to the feature/issue_23_mv_singularity development branch. I'm sure you got much further than Michell and I did!

**Comment by TatianaBurek** [comment]
@JohnHalleyGotway I get an error when try to push my work to this repo:
`Permission to NCAR/container-dtc-nwp.git denied to TatianaBurek`

**Comment by JohnHalleyGotway** [comment]
@TatianaBurek, I just added you to this repo with write permission. Please try again and let me know if you continue having access problems.

**Comment by TatianaBurek** [comment]
I updated Dockerfile_for_singularity with the addition of MariaDB.
 Commands that I use (please note that I was testing with the file name Dockerfile)
```
docker build --rm -t mariadb .
docker run --name=mariadb -d -p 8080:8080 -e MYSQL_ROOT_PASSWORD=mvuser -v <directory_on_your_computer>:/var/lib/mysql mariadb
docker exec --user root -it mariadb /bin/bash
```
In the container (as user root) start Tomcat:
```
cd /opt/tomcat/bin
./startup.sh
```

**Comment by michelleharrold** [comment]
Based on help from @TatianaBurek, we have a working example with the Hurricane Sandy case.

Commands needed (using feature/issue_23_mv_singularity):

Build image containing METviewer+MariaDB:
`cd $PROJ_DIR/container-dtc-nwp/components/metviewer/METviewer; docker build --rm -t dtcenter/metviewer_for_singularity -f Dockerfile_for_Singularity .`

setup ports, mounts, passwords, etc:
`docker run --name=metv -d -p 8080:8080 -e MYSQL_ROOT_PASSWORD=mvuser -v $CASE_DIR/metviewer/mysql:/var/lib/mysql -v ${PROJ_DIR}/container-dtc-nwp/components/scripts:/scripts -v ${CASE_DIR}/metprd:/data dtcenter/metviewer_for_singularity`

load data in a database:
`docker exec --user root -it metv /scripts/common/metv_load_singularity.ksh mv_sandy`

/bin/bash into the container to start Tomcat:
`docker exec --user root -it metv /bin/bash`
`cd /opt/tomcat/bin`
`./startup.sh`

**Comment by michelleharrold** [comment]
Update: This is the command to not have to /bin/bash into container to start Tomcat:

`docker exec --user root -it metv -w /opt/tomcat/bin ; ./startup.sh`

**Comment by fossell** [comment]
**Singularity method:**
After building the docker image called metviewer_for_singularity, we can pull that image with singularity to generate a .sif file (singularity image file).  We can then use the "[singularity instance](https://sylabs.io/guides/3.0/user-guide/running_services.html)" feature to instantiate an instance of the metviewer_for_singularity image, similar to the docker run command above to setup mounts and env variables etc. Once and instance is running, we can singularity exec using that instance to run the metv_load_singularity.ksh script, and then presumably the startup.sh as well.  

@fossell has built the Docker image metviewer_for_singularity and pushed it to her personal Dockerhub repo, so one can pull that directly without having to build the Docker image (useful if testing on Cheyenne where Docker is unavailable).

On Cheyenne (these steps assume you have already run the sandy case and have a PROJ_DIR established:
module load singularity 

Pull the image to create a .sif file.
```
cd ${PROJ_DIR}
singularity pull docker://fossell/metviewer_for_singularity:testing
```

Create an instance of the metviewer image while establishing bind mounts and env vars, etc. "metv" is name of instance:
```
singularity instance start -B /glade:/glade -B $CASE_DIR/metviewer/mysql:/var/lib/mysql -B ${PROJ_DIR}/container-dtc-nwp/components/scripts:/scripts -B ${CASE_DIR}/metprd:/data  --env MYSQL_ROOT_PASSWORD=mvuser metviewer_for_singularity_testing.sif metv
```

List instances:
`singularity exec instance list
`

> INSTANCE NAME    PID      IP    IMAGE
> metv             45349          /glade/scratch/fossell/rootfs-214317372/root

Run the instance invoking the desired metv_load script:
`singularity exec instance://metv-irish /scripts/common/metv_load_singularity.ksh mv_sandy
`
This results in lots of errors, e.g.:

> Mar 18, 2022 4:25:19 PM org.apache.tomcat.jdbc.pool.ConnectionPool init
> SEVERE: Unable to create initial connections of pool.
> java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Socket fail to connect to host:localhost, port:3306. Connection refused (Connection refused)
> ....
> java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Socket fail to connect to host:localhost, port:3306. Connection refused (Connection refused)

In attempt to try fixing a port issue, tried adding a port mapping using [--net and --network-args](https://sylabs.io/guides/3.0/user-guide/networking.html) to the instance start command, and singularity exec of the instance, both failed with errors.

In documentation it clarifies that you must be "root" or "[fakeroot](https://sylabs.io/guides/3.5/user-guide/fakeroot.html)" to leverage the --net and --network-args options.  

We attempted adding the --fakeroot option to both the instance start and the exec commands, but on Cheyenne received the following error:

> WARNING: fakeroot with unprivileged installation or 'allow setuid = no' could not use 'fakeroot' network, fallback to 'none' network

presumably meaning that we do have have permissions to use it on Cheyenne. 

On AWS however we were able to use it successfully, but unfortunately ended up with the same mysql errors
`singularity exec --fakeroot --net --network-args "portmap=80:8080/tcp" instance://metv-test

> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)

There appears to be an issue with launching/running mysql, we are unsure of how to debug this.

**Comment by TatianaBurek** [comment]
After debugging on AWS I think I understand why in our case simply building from Docker container to Singularity doesn't work.
1. fix-permissions.sh and docker-entrypoint.sh scripts don't get executed and/or executes with errors
2. problems with files ownership and permissions that are in the way of starting MariaDB

Here are the steps that I came up with that fix these problems:
1. build singularity sandbox from the docker container using 'fix-perms' options. I called it 'mfs' but you can give it more meaningful name. This step creates a directory 'mfs' in your home_dir:
`singularity build --sandbox --fix-perms --force  mfs docker://fossell/metviewer_for_singularity:testing`
2. Start the singularity instance as 'writable' and call it 'metv'
`singularity instance start --writable mfs metv`
3. Run init script  init_singularity.sh that initializes and starts MariaDB and Tomcat. Currently I have this script in my home directory. I added it to the GitHub and when "fossell/metviewer_for_singularity:testing" is rebuilt we can access it from mfs directory. For now, the command look like this:
`singularity exec --writable instance://metv bash init_singularity.sh `

When the script is done sometimes you need to press some key (Enter) to get back to the prompt. At this point the image is ready. To test the database :
```
singularity shell instance://metv
mysql -uroot -pmvuser
```
To stop the instance:
`singularity instance stop metv`

What is next:
- I hard-coded MYSQL_ROOT_PASSWORD in init_singularity.sh since we never change it. Let me know if this is a bad assumption and you need more flexibility. I can pass it as an argument instead.
- need to test METviewer capabilities like loading data
- we can try to replace executing init_singularity.sh with modifying Dockerfile_for_Singularity and execute "singularity run instance://metv" instead but it would require more work and I am not sure it would be possible in the end.

**Comment by michelleharrold** [comment]
Brushing the dust off this...

On AWS, I was able to successfully execute Singularity steps to load MET output and create a plot (via batch engine only -- I forgot to set up the port when I made the instance, and was having a heck of a time trying to get it set correctly).

Mods are currently in feature/issue_23_mv_singularity branch, so to test METviewer Singularity functionality, you need to clone this branch:
`git clone -b feature/issue_23_mv_singularity https://github.com/NCAR/container-dtc-nwp.git`

Then follow the tutorial instructions for running through end-to-end system to get MET output.

Next, pull the Singularity image (we will need to change this to be under dtcenter for the release):
`cd ${PROJ_DIR}`
`singularity pull docker://fossell/metviewer_for_singularity:testing`

Then, navigate to the METviewer directory and build Singularity sandbox from the docker container using 'fix-perms' options. It creates a metv4singularity directory:
`cd ${PROJ_DIR}/container-dtc-nwp/components/metviewer/METviewer`
`singularity build --sandbox --fix-perms --force metv4singularity docker://fossell/metviewer_for_singularity:testing`

Then, start the singularity instance as 'writable' and call it 'metv':
`singularity instance start --writable metv4singularity metv`

Run init script init_singularity.sh that initializes and starts MariaDB and Tomcat.
`singularity exec --writable instance://metv bash init_singularity.sh`

Finally, navigate to the scripts area, run a shell in the Singularity container, and load the MET output. The metv_load_singularity.ksh script requires to command-line arguments: 1) name of db, and 2) the ${CASE_DIR}:
`cd ${PROJ_DIR}/container-dtc-nwp/components/scripts/common`
`singularity shell instance://metv`
`./metv_load_singularity.ksh mv_sandy ${CASE_DIR}`

If you need to stop the instance:
`singularity instance stop metv`

I do have a question if @fossell, @JohnHalleyGotway, and @mkavulich could weigh in: We have example XMLs under each case, e.g., container-dtc-nwp/components/scripts/sandy_20121027/metviewer -- these work with our current paradigm, but need to updated if they want to work with mv_batch.sh (i.e., running on the command line). Do you want me to make a second set of XMLs to modify the host and management system to work with MariaDB/Singularity?

And a giant shoutout to @TatianaBurek for her help!

**Comment by fossell** [comment]
@michelleharrold - I don't have much experience in running metviewer in general, so I'm not sure I fully understand the options or different ways users will use the XMLs to give good guidance here.  What is mv_batch.sh?  If it makes most sense to have separate XMLs for examples, that's ok with me. But perhaps @JohnHalleyGotway has a more informed opinion.

**Comment by fossell** [comment]
I tried to test this on Cheyenne, but was pretty quickly hindered by permission and filesystem issues (similar to what we've seen before). So in the interest of time and resources, my initial thinking is that this feature will be a demonstration for AWS, and not generic and portable to any/all systems.

**Comment by fossell** [comment]
@michelleharrold - Is this ready for a PR then so we can assign and begin testing? Or do you want to hold off until a decision is made on the XMLs?

**Comment by michelleharrold** [comment]
@fossell - I decided just to add the XMLs right now. I made the final commits, so I will make the PR tonight!

**Comment by michelleharrold** [comment]
An update on run steps:

After the data has been loaded with the steps above, I have added scripts to run batch scripts via the command line (within the Singularity shell):

`cd ${PROJ_DIR}/container-dtc-nwp/components/scripts/sandy_20121027/metviewer`
`./metv_plot_singularity.ksh ${CASE_DIR}`

Output goes to: `${CASE_DIR}/metviewer/plots,` and you can use display to view the images.
