### ISSUE TITLE
Multi-node Singularity

### ISSUE THREAD

**Issue by mkavulich** [NCAR/container-dtc-nwp#24]
The Singularity native multi-node capability is one of its main advantages. We should put effort into testing this capability to ensure it will work in an HPC environment such as Cheyenne.

## Todo
 - [ ] Create dockerhub tags for multinode capability
 - [ ] Create documentation for multinode capability on Online Tutorial

**Comment by jeffreycunn** [comment]
Sounds interesting! I was testing the tutorial's Singularity based WRF on a Google Cloud Slurm cluster recently, but I wasn't able to run on multiple nodes. Actually, I was only able to run WRF on the login node...I am not super familiar with Singularity or Slurm, but have decent experience on GCP.  Is this something you think NCAR will put some effort towards?  I may be able to run a few GCP tests here and there if it could help.
