### ISSUE TITLE
Fix python scripts to process subset of fhrs for derecho

### ISSUE THREAD

**Issue by fossell** [NCAR/container-dtc-nwp#33]
For questions, ask @michelleharrold.

**Comment by JohnHalleyGotway** [comment]
Running WRF and UPP produces the following wrfprs files:
```
ls -1 postprd/wrfprs*
postprd/wrfprs_d01.00
postprd/wrfprs_d01.03
postprd/wrfprs_d01.06
postprd/wrfprs_d01.09
postprd/wrfprs_d01.12
postprd/wrfprs_d01.15
postprd/wrfprs_d01.18
postprd/wrfprs_d01.21
postprd/wrfprs_d01.24
postprd/wrfprs_d02.15
postprd/wrfprs_d02.18
postprd/wrfprs_d02.21
```
The run_python.ksh script loops from fhr_beg (00) to fhr_end (24) every fhr_inc (03) hours and attempts to create plots for each output time, even though no d02 output exists for some of the times.
@michelleharrold is the task here to just update the run_python.ksh to skip over files that do not actually exist?

**Comment by michelleharrold** [comment]
@JohnHalleyGotway - yes, the goal is to avoid the the error message that the files don't exist. Since we changed d02 to only be a subset of hours being run (as compared to d01), we should probably update the Python piece to account for this. (We weren't planning on reducing runtime with this change).

**Comment by JohnHalleyGotway** [comment]
Ran the derecho case to test these changes. Here's the python command:
```
docker run --rm -it -e LOCAL_USER_ID=`id -u $USER` \
-v ${PROJ_DIR}/container-dtc-nwp/components/scripts/common:/home/scripts/common \
-v ${PROJ_DIR}/container-dtc-nwp/components/scripts/derecho_20120629:/home/scripts/case \
-v ${CASE_DIR}/postprd:/home/postprd -v ${CASE_DIR}/pythonprd:/home/pythonprd \
--name run-derecho-python dtcenter/python:3.4 /home/scripts/common/run_python.ksh
```
The existing script produces 6 traceback errors for the 6 files that do not exist:
```
grep Traceback run_python.log | wc -l
       6
```
While the modified version produces none:
```
grep Traceback run_python_feature_33.log | wc -l
       6
```
[run_python.log](https://github.com/NCAR/container-dtc-nwp/files/7010390/run_python.log)
[run_python_feature_33.log](https://github.com/NCAR/container-dtc-nwp/files/7010391/run_python_feature_33.log)
