### ISSUE TITLE
Fix WPS script to only run ungrib on case date files

### ISSUE THREAD

**Issue by michelleharrold** [NCAR/container-dtc-nwp#51]
The WPS script's current functionality is to ungrib all files under the model_data/gfs directory. This causes the ungrib step to be unnecessarily slow. It would be good to fix the functionality to only run on the case-specific files.

**Comment by fossell** [comment]
This will be done in separate PR than #54.
For Fix WPS script to only run ungrib on case date files #51:
an extra environmental variable (case_name) was added to set_env.ksh of each case where user can indicate the case name, e.g. "sandy".
The common run_wps.ksh script was updated to removed the hard coded subdirectory "gfs" from the path pointing to the model input data.
Tests performed:
Sandy on MacOS with main branch wps_wrf image built locally. Successful through WPS/metgrid steps.
TODO: Complete end to test, discuss with group preferred directory organization and naming, Modify/update online tutorial steps for downloading data (e.g. re-tar into preferred directory structure, or add mv commands)

**Comment by fossell** [comment]
This will need to be done with new release v3.5 since input data will need to be packaged in new directory structure.
