### ISSUE TITLE
Additional tasks necessary to complete v3.5 release

### ISSUE THREAD

**Issue by jwolff-ncar** [NCAR/container-dtc-nwp#58]
- [x] Update online tutorial to list the new version 

- [x] Reorganize data on mohawk & glade filesystem:
Done by @fossell for NCAR/container-dtc-nwp#55

- [x] Update DockerHub images

- [x] Test end-to-end tutorial instructions

- [x] Update DTC website release information

- [x] Update the Docker Run Script in:
https://github.com/NCAR/container-dtc-nwp/blob/main/components/scripts/common/docker_run_case.ksh

- [x] Remove announcements about all releases prior to v3.5 from the DTC website at:
https://dtcenter.org/community-code/numerical-weather-prediction-nwp-containers/download

**Comment by fossell** [comment]
Case data tarballs have been re-packaged using new paths, e.g. model_data/sandy.  All updated tarballs staged in "data_temp" on both Mohawk (dfiles/container_nwp_tutorial/tar_files/data_temp) and Glade (/glade/p/ral/jntp/NWP_containers/data_temp). Should replace files one directory up when ready (depends on scripts updates).

**Comment by JohnHalleyGotway** [comment]
Testing task assignments for the corresponding PR:
- [ ] @JohnHalleyGotway: Test the updated docker_run_case.ksh script on all 3 cases on your laptop.
- [ ] @mkavulich: Test Singularity for all 3 cases on AWS. Also test Docker for all 3 cases on Mac Catalina version.
- [ ] @michelleharrold: Test Docker all 3 cases on AWS.
- [ ] @jwolff-ncar: Test Docker all 3 cases on Mac BigSur laptop.

**Comment by fossell** [comment]
@mkavulich @jwolff-ncar @michelleharrold - I believe I am ready for your testing now. 
@JohnHalleyGotway - please see #66 for updated run script to test. Will need to retag v3.5 after that PR is tested and merged.

**Comment by fossell** [comment]
Release complete!
