### ISSUE TITLE
End-To-End run scripts to facilitate testing.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/container-dtc-nwp#7]
These scripts are intended to facilitate automated testing of containers.
- docker_load_tutorial.ksh script to load all the data and s/w containers.
- run_tutorial_case.ksh script to run all commands for the specified tutorial case (sandy, snow, or derecho).

**Comment by JohnHalleyGotway** [comment]
Committed scripts/common/docker_load_images.ksh and docker_run_case.ksh to support automated building/testing of containers.  However, I was not yet able to do sufficient testing of these scripts since I'm having space issues on my laptop.

**Comment by JohnHalleyGotway** [comment]
At the containers project meeting on 4/27/21, we discussed that if we decide to write these scripts, we should also consider running them in an automated way via GitHub Actions. Consider spinning that off as a separate issue.

**Comment by fossell** [comment]
Update the original scripts to pull images from dockerhub instead of downloading tarballs.

**Comment by JohnHalleyGotway** [comment]
Be sure to test c5 and m5.2xlarge on AWS.
Update any existing run scripts and keep track of runtime for each call.
